version: 2.1
workflows:
  testing:
    jobs:
      - windows-default-aws

jobs:
  windows-default-aws:
    machine:
      image: windows-default
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          when: always
          name: "Users circleci .ssh"
          command: |
                   Get-ChildItem C:\Users\circleci\.ssh
          shell: powershell.exe
      - run: 
          name: "dir"
          command: dir
          shell: cmd.exe  
